version: "3.8"

services:
  postgres:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: phandat
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: e-learning
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
