name: Test Runner

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run test
        run: echo "✅ Hello from your self-hosted runner!"